apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager-prometheus-discovery
  selfLink: /api/v1/namespaces/kube-system/endpoints/kube-controller-manager-prometheus-discovery
subsets:
- addresses:
  - ip: 172.16.0.27
    nodeName: master
    targetRef:
      kind: Pod
      name: kube-controller-manager-master
      namespace: kube-system
      resourceVersion: "16761553"
      uid: 781232a6-af2d-11e9-858a-fa163eb7a9f3
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
