apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kube-controller-manager"},"name":"kube-controller-manager-prometheus-discovery","namespace":"kube-system"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":10252,"targetPort":10252}],"selector":{"component":"kube-controller-manager"}}}
  creationTimestamp: null
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager-prometheus-discovery
  selfLink: /api/v1/namespaces/kube-system/services/kube-controller-manager-prometheus-discovery
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  selector:
    component: kube-controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
