apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: deployment-controller
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/deployment-controller
secrets:
- name: deployment-controller-token-4bp2f
