apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2019-03-20T15:39:57Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  resourceVersion: "185"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/kubeadm%3Anodes-kubeadm-config
  uid: 6a698265-4b26-11e9-8f3b-fa163eb7a9f3
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
