apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-03-20T15:39:57Z"
  name: deployment-controller
  namespace: kube-system
  resourceVersion: "195"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/deployment-controller
  uid: 6a6ed913-4b26-11e9-8f3b-fa163eb7a9f3
secrets:
- name: deployment-controller-token-4bp2f
