apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kube-controller-manager"},"name":"kube-controller-manager-prometheus-discovery","namespace":"kube-system"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":10252,"targetPort":10252}],"selector":{"component":"kube-controller-manager"}}}
  creationTimestamp: "2019-03-20T15:49:09Z"
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
  resourceVersion: "1611"
  selfLink: /api/v1/namespaces/kube-system/services/kube-controller-manager-prometheus-discovery
  uid: b34efd2c-4b27-11e9-8f3b-fa163eb7a9f3
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  selector:
    component: kube-controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
