apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXlNREUxTXprek1sb1hEVEk1TURNeE56RTFNemt6TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUE9ICnl4ais2bEFUTVJOdk1GYkxhK1FLcjFpMkErdzVod2hvOHIvM2RwbkNCVTgzNmE0dnR0ZUFKK1pXRlVZZ2JuakkKekJ5L2pHRm92QjFEMFdWYXY5UldIcmZFL2N1cndJNWE0RVZwY1E4KytqWklYc1N5TkhmNVhEd3JsSDZ0Y3RIYwprNm9iS3Y2dDJORmVNZ2V4WmV1MGxEZFlMQ0lidmFoSCt1ZVQ4cFowN3BXN0hCeEdWaDYzSDFqSC9GSGRNWjE0CnJGc3hPOTY5YTNrVllOTzJhUzNpOG93ajJCSUsyWVcwM2I4ZWhJdkxhdXhIeWcrNEYvdTF0TWFYMWJ1eGROTXQKV2lPcDIzOGdCeU1KS1N1UHNYZVZKM2VWMXN0OVBEMEZKODNST1JpQ2MzcEh2cmFGZ05MbmkzVnRiMG9FeTRyTwpPRFRCY2h3aFc4dlY1WkRmWlVNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKV25vME1qVlpMMkQ2Uk5aZmZza2NSL3c1bDcKUUdpRzk0M29Oc3h5MmJueVROa3dGQk0wb3AyVEk5S0JFN0ZiVGZLM3AwSjB2aCtJVnlIdjdmNjI3QTVMclcxeQpIeHJGQ0xVM2c5TzJSU3p1UUtFVHJtN0NCdEVtMWJ3RWtGdEIwOFhkeGM0dmhHQ0YzVnNLa255TUE1UUU2Y3UvCitjWFNsV3M4V2E0RzZIdWxRQ00rNkpaL1JoWTcrRkZqRnRvNzhXMVlkRnZnQW1rZGFlL0FVVVhQSlBmcGZ4TU4KeldaeklWTUhqVXFwQ3hGaW01MGlkZEwzWVdoUDI1TkVFNEwrR2FTaGdwT2RBTXh2N1gwcWRZRDZJWWdhQUd3dApWV1ZlVE5KOTA0YXEwUzcvOE5WenpQcTdlU1RqS1I4MGhvTUJ3RWVUY1NRMGhBTTdGSUFkdk5BRGhWND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://172.16.0.27:6443
      name: ""
    contexts: []
    current-context: ""
    kind: Config
    preferences: {}
    users: []
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-20T15:39:58Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "16761581"
  selfLink: /api/v1/namespaces/kube-public/configmaps/cluster-info
  uid: 6b105ca3-4b26-11e9-8f3b-fa163eb7a9f3
