apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"run":"haproxy-ingress"},"name":"haproxy-ingress","namespace":"haproxy-controller"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"haproxy-ingress"}},"template":{"metadata":{"labels":{"run":"haproxy-ingress"}},"spec":{"containers":[{"args":["--default-ssl-certificate=default/tls-secret","--configmap=default/haproxy-configmap","--default-backend-service=haproxy-controller/ingress-default-backend"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"haproxytech/kubernetes-ingress","livenessProbe":{"httpGet":{"path":"/healthz","port":1042}},"name":"haproxy-ingress","ports":[{"containerPort":80,"name":"http"},{"containerPort":443,"name":"https"},{"containerPort":1024,"name":"stat"}],"resources":{"requests":{"cpu":"500m","memory":"50Mi"}}}],"serviceAccountName":"haproxy-ingress-service-account"}}}}
  creationTimestamp: "2019-07-18T13:21:32Z"
  generation: 5
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: haproxy-controller
  resourceVersion: "16842527"
  selfLink: /apis/extensions/v1beta1/namespaces/haproxy-controller/deployments/haproxy-ingress
  uid: f5d6ad49-a95e-11e9-858a-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: haproxy-ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: haproxy-ingress
    spec:
      containers:
      - args:
        - --default-ssl-certificate=default/tls-secret
        - --configmap=default/haproxy-configmap
        - --default-backend-service=haproxy-controller/ingress-default-backend
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: haproxytech/kubernetes-ingress
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 1042
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: haproxy-ingress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 1024
          name: stat
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: haproxy-ingress-service-account
      serviceAccountName: haproxy-ingress-service-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-18T13:21:32Z"
    lastUpdateTime: "2019-07-22T21:43:41Z"
    message: ReplicaSet "haproxy-ingress-69599bd497" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-26T13:06:13Z"
    lastUpdateTime: "2019-07-26T13:06:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
