apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-07-26T13:05:55Z"
  generateName: haproxy-ingress-69599bd497-
  labels:
    pod-template-hash: 69599bd497
    run: haproxy-ingress
  name: haproxy-ingress-69599bd497-qjf78
  namespace: haproxy-controller
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: haproxy-ingress-69599bd497
    uid: f5d7c3de-a95e-11e9-858a-fa163eb7a9f3
  resourceVersion: "16842524"
  selfLink: /api/v1/namespaces/haproxy-controller/pods/haproxy-ingress-69599bd497-qjf78
  uid: 1a918d39-afa6-11e9-858a-fa163eb7a9f3
spec:
  containers:
  - args:
    - --default-ssl-certificate=default/tls-secret
    - --configmap=default/haproxy-configmap
    - --default-backend-service=haproxy-controller/ingress-default-backend
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: haproxytech/kubernetes-ingress
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 1042
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: haproxy-ingress
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
      protocol: TCP
    - containerPort: 1024
      name: stat
      protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: haproxy-ingress-service-account-token-md885
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-3
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: haproxy-ingress-service-account
  serviceAccountName: haproxy-ingress-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: haproxy-ingress-service-account-token-md885
    secret:
      defaultMode: 420
      secretName: haproxy-ingress-service-account-token-md885
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-26T13:05:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-26T13:06:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-26T13:06:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-26T13:05:55Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5b62c55862fc34c1fe4ccbf02966bfa38b68c6feb0b417a9a7336fa233d3aaef
    image: haproxytech/kubernetes-ingress:latest
    imageID: docker-pullable://haproxytech/kubernetes-ingress@sha256:f926c7c0232b5653f25ba3f3be27bfe76eafec5eeb3e95b062f9badf164cc0b7
    lastState: {}
    name: haproxy-ingress
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-26T13:06:12Z"
  hostIP: 172.16.0.7
  phase: Running
  podIP: 10.42.0.6
  qosClass: Burstable
  startTime: "2019-07-26T13:05:55Z"
