apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"haproxy-ingress-service-account","namespace":"haproxy-controller"}}
  creationTimestamp: "2019-07-18T13:21:32Z"
  name: haproxy-ingress-service-account
  namespace: haproxy-controller
  resourceVersion: "15788026"
  selfLink: /api/v1/namespaces/haproxy-controller/serviceaccounts/haproxy-ingress-service-account
  uid: f5be6f1b-a95e-11e9-858a-fa163eb7a9f3
secrets:
- name: haproxy-ingress-service-account-token-md885
