apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"ingress-default-backend"},"name":"ingress-default-backend","namespace":"haproxy-controller"},"spec":{"ports":[{"name":"port-1","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"run":"ingress-default-backend"}}}
  creationTimestamp: "2019-07-18T13:21:32Z"
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: haproxy-controller
  resourceVersion: "15788039"
  selfLink: /api/v1/namespaces/haproxy-controller/services/ingress-default-backend
  uid: f5d23ddf-a95e-11e9-858a-fa163eb7a9f3
spec:
  clusterIP: 10.97.77.104
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: ingress-default-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
