apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-07-27T00:29:38Z"
  generateName: prometheus-adapter-77c867454d-
  labels:
    name: prometheus-adapter
    pod-template-hash: 77c867454d
  name: prometheus-adapter-77c867454d-q66gv
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-adapter-77c867454d
    uid: 62fdfa93-5019-11e9-8f3b-fa163eb7a9f3
  resourceVersion: "16905868"
  selfLink: /api/v1/namespaces/monitoring/pods/prometheus-adapter-77c867454d-q66gv
  uid: 9e57b06b-b005-11e9-858a-fa163eb7a9f3
spec:
  containers:
  - args:
    - --cert-dir=/var/run/serving-cert
    - --config=/etc/adapter/config.yaml
    - --logtostderr=true
    - --metrics-relist-interval=10s
    - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
    - --secure-port=6443
    image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
    imagePullPolicy: IfNotPresent
    name: prometheus-adapter
    ports:
    - containerPort: 6443
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /var/run/serving-cert
      name: volume-serving-cert
    - mountPath: /etc/adapter
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-adapter-token-lnck4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-3
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: prometheus-adapter
  serviceAccountName: prometheus-adapter
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmpfs
  - emptyDir: {}
    name: volume-serving-cert
  - configMap:
      defaultMode: 420
      name: adapter-config
    name: config
  - name: prometheus-adapter-token-lnck4
    secret:
      defaultMode: 420
      secretName: prometheus-adapter-token-lnck4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T00:29:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T00:29:41Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T00:29:41Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T00:29:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b066b5d002fda929fcf95956ceeb159171b1baf1573330dcf2d573a426e4d455
    image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
    imageID: docker-pullable://quay.io/coreos/k8s-prometheus-adapter-amd64@sha256:cd44106e853564873e6bf261a672f0ee2122cdbd70800dafce2c3c26d0b4be95
    lastState: {}
    name: prometheus-adapter
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-27T00:29:41Z"
  hostIP: 172.16.0.7
  phase: Running
  podIP: 10.42.0.3
  qosClass: BestEffort
  startTime: "2019-07-27T00:29:38Z"
