apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"prometheus-k8s-config","namespace":"monitoring"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["get"]}]}
  creationTimestamp: "2019-03-20T15:49:09Z"
  name: prometheus-k8s-config
  namespace: monitoring
  resourceVersion: "1628"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/monitoring/roles/prometheus-k8s-config
  uid: b35cec8d-4b27-11e9-8f3b-fa163eb7a9f3
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
