apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-operator","namespace":"monitoring"}}
  creationTimestamp: "2019-03-20T15:49:08Z"
  name: prometheus-operator
  namespace: monitoring
  resourceVersion: "1475"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-operator
  uid: b2b8e325-4b27-11e9-8f3b-fa163eb7a9f3
secrets:
- name: prometheus-operator-token-n7tk5
