apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-adapter","namespace":"monitoring"}}
  creationTimestamp: "2019-03-20T15:49:09Z"
  name: prometheus-adapter
  namespace: monitoring
  resourceVersion: "1601"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-adapter
  uid: b346d5f8-4b27-11e9-8f3b-fa163eb7a9f3
secrets:
- name: prometheus-adapter-token-lnck4
