apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"k8s-app":"prometheus-operator"},"name":"prometheus-operator","namespace":"monitoring"},"spec":{"endpoints":[{"honorLabels":true,"port":"http"}],"selector":{"matchLabels":{"k8s-app":"prometheus-operator"}}}}
  creationTimestamp: "2019-03-20T15:49:08Z"
  generation: 1
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
  resourceVersion: "1476"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prometheus-operator
  uid: b2d743dc-4b27-11e9-8f3b-fa163eb7a9f3
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      k8s-app: prometheus-operator
