apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"alertmanager-main","namespace":"monitoring"}}
  creationTimestamp: "2019-03-20T15:49:08Z"
  name: alertmanager-main
  namespace: monitoring
  resourceVersion: "1485"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/alertmanager-main
  uid: b2e21c9b-4b27-11e9-8f3b-fa163eb7a9f3
secrets:
- name: alertmanager-main-token-fpt2z
