apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-k8s","namespace":"monitoring"}}
  creationTimestamp: "2019-03-20T15:49:09Z"
  name: prometheus-k8s
  namespace: monitoring
  resourceVersion: "1640"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-k8s
  uid: b375ee52-4b27-11e9-8f3b-fa163eb7a9f3
secrets:
- name: prometheus-k8s-token-7gkpf
