kind: Service
apiVersion: v1
metadata:
  namespace: ingress-nginx
  name: nginx-ingress-prometheus-discovery
  labels:
    k8s-app: ingress
spec:
  selector:
    app: ingress-nginx
  type: ClusterIP
  #  clusterIP: None    
  ports:
  - name: http
    port: 80
    protocol: TCP
