deploy:
  sut_worker: worker-3
  benchmark_worker: worker-2
  service_ip: [SERVICE_IP] #filled automatically
  fortio_ip: 10.104.203.29 #filley automatically
measurement:
  max_cpu: 7
  cpus: ['100m','100m','100m','100m']
  pods: [1,2,5,10]
  start_qps: 50
  step: 50
  max_benchmark: 20
  max_request_lost: 10 #percent of lost requests, if we reach this, the loop will stop
  benchmark_time: 60 # time of one benchmark test (in seconds)
  number_of_measurements: 2
