apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  selfLink: /api/v1/namespaces/haproxy-controller/endpoints/haproxy-ingress
subsets:
- addresses:
  - ip: 10.42.0.6
    nodeName: worker-3
    targetRef:
      kind: Pod
      name: haproxy-ingress-69599bd497-qjf78
      namespace: haproxy-controller
      resourceVersion: "16842524"
      uid: 1a918d39-afa6-11e9-858a-fa163eb7a9f3
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: stat
    port: 1024
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
