apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: haproxy-ingress-69599bd497-
  labels:
    pod-template-hash: 69599bd497
    run: haproxy-ingress
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: haproxy-ingress-69599bd497
    uid: f5d7c3de-a95e-11e9-858a-fa163eb7a9f3
  selfLink: /api/v1/namespaces/haproxy-controller/pods/haproxy-ingress-69599bd497-qjf78
spec:
  containers:
  - args:
    - --default-ssl-certificate=default/tls-secret
    - --configmap=default/haproxy-configmap
    - --default-backend-service=haproxy-controller/ingress-default-backend
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: haproxytech/kubernetes-ingress
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 1042
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: haproxy-ingress
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
      protocol: TCP
    - containerPort: 1024
      name: stat
      protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: haproxy-ingress-service-account-token-md885
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-3
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: haproxy-ingress-service-account
  serviceAccountName: haproxy-ingress-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: haproxy-ingress-service-account-token-md885
    secret:
      defaultMode: 420
      secretName: haproxy-ingress-service-account-token-md885
status:
  phase: Pending
  qosClass: Burstable
