apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: ingress-default-backend-55c6dddf9b-
  labels:
    pod-template-hash: 55c6dddf9b
    run: ingress-default-backend
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ingress-default-backend-55c6dddf9b
    uid: f5cd5f5d-a95e-11e9-858a-fa163eb7a9f3
  selfLink: /api/v1/namespaces/haproxy-controller/pods/ingress-default-backend-55c6dddf9b-mksrv
spec:
  containers:
  - image: gcr.io/google_containers/defaultbackend:1.0
    imagePullPolicy: IfNotPresent
    name: ingress-default-backend
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4f88z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-4f88z
    secret:
      defaultMode: 420
      secretName: default-token-4f88z
status:
  phase: Pending
  qosClass: BestEffort
