apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"haproxy-ingress-service-account","namespace":"haproxy-controller"}}
  creationTimestamp: null
  name: haproxy-ingress-service-account
  selfLink: /api/v1/namespaces/haproxy-controller/serviceaccounts/haproxy-ingress-service-account
secrets:
- name: haproxy-ingress-service-account-token-md885
