apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  selfLink: /api/v1/namespaces/monitoring/endpoints/prometheus-operator
subsets:
- addresses:
  - ip: 10.42.0.1
    nodeName: worker-3
    targetRef:
      kind: Pod
      name: prometheus-operator-7cb68545c6-d7f2w
      namespace: monitoring
      resourceVersion: "16842492"
      uid: 1a8e5b04-afa6-11e9-858a-fa163eb7a9f3
  ports:
  - name: http
    port: 8080
    protocol: TCP
