apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    alertmanager: main
  name: alertmanager-main
  selfLink: /api/v1/namespaces/monitoring/endpoints/alertmanager-main
subsets:
- addresses:
  - ip: 10.36.0.3
    nodeName: worker-2
    targetRef:
      kind: Pod
      name: alertmanager-main-0
      namespace: monitoring
      resourceVersion: "1850"
      uid: b9f46358-4b27-11e9-8f3b-fa163eb7a9f3
  - ip: 10.36.0.4
    nodeName: worker-2
    targetRef:
      kind: Pod
      name: alertmanager-main-2
      namespace: monitoring
      resourceVersion: "1967"
      uid: ccc6f06e-4b27-11e9-8f3b-fa163eb7a9f3
  - ip: 10.42.0.2
    nodeName: worker-3
    targetRef:
      kind: Pod
      name: alertmanager-main-1
      namespace: monitoring
      resourceVersion: "16842570"
      uid: 1a91b15b-afa6-11e9-858a-fa163eb7a9f3
  ports:
  - name: web
    port: 9093
    protocol: TCP
