apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: prometheus-adapter-77c867454d-
  labels:
    name: prometheus-adapter
    pod-template-hash: 77c867454d
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-adapter-77c867454d
    uid: 62fdfa93-5019-11e9-8f3b-fa163eb7a9f3
  selfLink: /api/v1/namespaces/monitoring/pods/prometheus-adapter-77c867454d-q66gv
spec:
  containers:
  - args:
    - --cert-dir=/var/run/serving-cert
    - --config=/etc/adapter/config.yaml
    - --logtostderr=true
    - --metrics-relist-interval=10s
    - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
    - --secure-port=6443
    image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
    imagePullPolicy: IfNotPresent
    name: prometheus-adapter
    ports:
    - containerPort: 6443
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /var/run/serving-cert
      name: volume-serving-cert
    - mountPath: /etc/adapter
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-adapter-token-lnck4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-3
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: prometheus-adapter
  serviceAccountName: prometheus-adapter
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmpfs
  - emptyDir: {}
    name: volume-serving-cert
  - configMap:
      defaultMode: 420
      name: adapter-config
    name: config
  - name: prometheus-adapter-token-lnck4
    secret:
      defaultMode: 420
      secretName: prometheus-adapter-token-lnck4
status:
  phase: Pending
  qosClass: BestEffort
