apiVersion: v1
data:
  prometheus.yaml.gz: H4sIAAAAAAAA/+ycUW/bNhCA3/0r+NCHpIWiBMOAQH0asD2u6/swEGfyLLOmSI6k3GTL/vsgWrKlWHLttrJVmG8JZR7vjrqPvBOlXOo5yGxGCK5BluCFVlQoj3YNMiM/uxkhjlkw+LoVnzxaBZJKmKN0lQhCjNUF+iWWLiOFVsJrK1Serh7dq8vUopGCQUbe3Hz841f64Zfff7ud2VIiXQiJLpslJEXP0l2XtLrqWg3J6tElVWPokdynb++eoZCzWl+m1ULkQdInPacKCuwoBRKtL0BBjja9nxGy1ErbxhyyAOlwRsiqnKNV6NFRx3dCCUmI1RIzgoobLZTfmFgN4wwwrD1StzT/JC0N+lz7030lxmLQojsasGpyMrJCNEGa06Vl2PF/Qigt0ANta412LZrf0bbVoYvFHJ8yUoBQ3zRM4wZqtPXB223xn3EepJ8qDDi36Bz1YHP0dCUUP7nTVheHBix4bTPyvq3cB83x/c3d29u60UhgWKDyGXnz78N/obWWFRTPiNIcp2vPR81PM8dofoo123u8zzOta0cLbG7RrWVdmfXlUyQazYeknWjsF3T7pOeDbk5e/baZ0P0OVXgMYIppi1y5MxKqkpe4Z+ex6EPUQ8D/HMGipV6vUAVkZyRdg01tqVKHzKJ36U6xO6HT2pHAmC6VT0PPcVm3enQUjGmHRrCNKzci6gr0VjA3XTxE3EXcjYO7b47SocHCPN/cvRue4+NZ28TnAG9zCwtQMJkd4Qa3Y+4Iu4Ss7R8RkEvvzXRpEukY6XjZzWCIjwE6LcFY/fR8RjrVIyZMK2+1lCFt7C8JjAgpW6oOQmqlhMqrYBgRVs6Dn25wR1hFWF0WViE+BmAVki0wolLkrDU2jgsopR8usDm2xErZCrXV/166etiNEKEcstIidSth6BqtWDzv1CWEwVflvAzumPV1BFQ+qX226/SDZNZMF0Yr3N4QIXi3M/0dBzJWrwXvlio73hpzkxpz+Aj+qwP/d+DBObL4Jj432TztZd2AKZVbKG3rhJ5xesNxXua5UPkLF271YvHvEp1/2TDt9u5t6NHQhlt9MIndH2SLRwq8EM4JrehuU91qlOBRMRGczLTijo4ytvNoTh710Eq/MyY5/2O1LxStR3+uNlRr3nfKyItWEuvPce2Ka9d068+vgvSiC9ghnFc5Ei9lpHjbFxHeEd4R3hHeh54gbojhwWPzyx6Celue/1li+zifFwXq0m8bv6YgVhvxI1SsBsnenqex60nJ9pTdJFkY2R7ZfuVsr0P0eLI/TOSYSKT4+SjuUC6mS71I8Ujxq6d4CNEDFJfoz7cp/0JV46rRLdGPv+uORZWI7IjsiSP7iKpKRe39DfcFqV3rTA34ZUbSJilgwNfCaRu5HrkeuR65Hrn+HR51JkQUkHcwwLTyIBRaevMnJP/Qv97dbu7Xrz8p0xKp0H/WdkU9M7R0kCP12oN8adpL3m334FaOhlLECzMllRo4hTXa6icP9+52X7WBta6iQIJPFfom9276NS5onfmIh07jchaXs2tdzoaQ3fpOybR4PSIpdzZ3dv+PY1bg44dEIiCvEJDHMurAh0RaH07SBsN0X+hcynk3bz12x5fbI6AioC73cnv4CJlQIWMMf/fXBJoIDZfqVL4nrJtvyTXC6vcsaiEG/JIaiwvxlJF0cze1UtjQMEi7Id71Ee8V8/ao18u9XhD1oujIOdu98tNyRXPu7FtHG0BfZ3P2fwAAAP//Fq40OFJQAAA=
kind: Secret
metadata:
  annotations:
    generated: "true"
  creationTimestamp: null
  labels:
    managed-by: prometheus-operator
  name: prometheus-k8s
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: k8s
    uid: b3561804-4b27-11e9-8f3b-fa163eb7a9f3
  selfLink: /api/v1/namespaces/monitoring/secrets/prometheus-k8s
type: Opaque
