apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-k8s","namespace":"monitoring"}}
  creationTimestamp: null
  name: prometheus-k8s
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-k8s
secrets:
- name: prometheus-k8s-token-7gkpf
