apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-adapter","namespace":"monitoring"}}
  creationTimestamp: null
  name: prometheus-adapter
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-adapter
secrets:
- name: prometheus-adapter-token-lnck4
