apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"alertmanager-main","namespace":"monitoring"}}
  creationTimestamp: null
  name: alertmanager-main
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/alertmanager-main
secrets:
- name: alertmanager-main-token-fpt2z
