apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    operated-alertmanager: "true"
  name: alertmanager-operated
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    name: main
    uid: b2dce8fb-4b27-11e9-8f3b-fa163eb7a9f3
  selfLink: /api/v1/namespaces/monitoring/services/alertmanager-operated
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: mesh
    port: 6783
    protocol: TCP
    targetPort: 6783
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
