apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"prometheus-operator","namespace":"monitoring"}}
  creationTimestamp: null
  name: prometheus-operator
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-operator
secrets:
- name: prometheus-operator-token-n7tk5
