action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 718
deprecatedFirstTimestamp: "2019-07-26T12:55:12Z"
deprecatedLastTimestamp: "2019-07-27T20:18:34Z"
deprecatedSource:
  component: horizontal-pod-autoscaler
eventTime: null
kind: Event
metadata:
  creationTimestamp: null
  name: test-deployment.15b4f63d0a8abfbb
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/test-deployment.15b4f63d0a8abfbb
note: 'unable to get metrics for resource cpu: no metrics returned from resource metrics
  API'
reason: FailedGetResourceMetric
regarding:
  apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  name: test-deployment
  namespace: default
  resourceVersion: "17015960"
  uid: 028b4ceb-aedc-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Warning
