apiVersion: v1
count: 11
eventTime: null
firstTimestamp: "2019-07-27T12:19:56Z"
involvedObject:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17014887"
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:53:31Z"
message: Scaled up replica set nodejs-ml-deployment-6d5565df57 to 2
metadata:
  creationTimestamp: null
  name: nodejs-ml-deployment.15b542e4d3518da2
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment.15b542e4d3518da2
reason: ScalingReplicaSet
reportingComponent: ""
reportingInstance: ""
source:
  component: deployment-controller
type: Normal
