apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:53:31Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17023075"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:53:31Z"
message: 'Created pod: nodejs-ml-deployment-6d5565df57-wtf5c'
metadata:
  creationTimestamp: null
  name: nodejs-ml-deployment-6d5565df57.15b55ba56e53e0da
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b55ba56e53e0da
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
