action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 11
deprecatedFirstTimestamp: "2019-07-27T12:38:56Z"
deprecatedLastTimestamp: "2019-07-27T20:19:28Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: null
  name: nodejs-ml-deployment.15b543ee60b90342
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment.15b543ee60b90342
note: Scaled down replica set nodejs-ml-deployment-6d5565df57 to 1
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17014781"
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
