apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"test-ingress","namespace":"default"},"spec":{"rules":[{"host":"testserver","http":{"paths":[{"backend":{"serviceName":"test-service","servicePort":8080},"path":"/"}]}}]}}
  creationTimestamp: null
  generation: 1
  name: test-ingress
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/test-ingress
spec:
  rules:
  - host: testserver
    http:
      paths:
      - backend:
          serviceName: test-service
          servicePort: 8080
        path: /
status:
  loadBalancer: {}
