apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"nodejs-cpu-ingress","namespace":"default"},"spec":{"rules":[{"host":"nodejs-cpu-app","http":{"paths":[{"backend":{"serviceName":"nodejs-cpu-service","servicePort":3000},"path":"/"}]}}]}}
  creationTimestamp: null
  generation: 1
  name: nodejs-cpu-ingress
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nodejs-cpu-ingress
spec:
  rules:
  - host: nodejs-cpu-app
    http:
      paths:
      - backend:
          serviceName: nodejs-cpu-service
          servicePort: 3000
        path: /
status:
  loadBalancer: {}
