apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: model-deployment-55485dbf7b-
  labels:
    app: model
    pod-template-hash: 55485dbf7b
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: model-deployment-55485dbf7b
    uid: 67468f30-84ad-11e9-8f3b-fa163eb7a9f3
  selfLink: /api/v1/namespaces/default/pods/model-deployment-55485dbf7b-hvh4f
spec:
  containers:
  - image: balazska/test-server:fixed-serving-v2
    imagePullPolicy: IfNotPresent
    name: test-server
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /media
      name: log
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kh6h8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /media
      type: Directory
    name: log
  - name: default-token-kh6h8
    secret:
      defaultMode: 420
      secretName: default-token-kh6h8
status:
  phase: Pending
  qosClass: Burstable
