apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2019-03-20T15:39:56Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:deployment-controller
  resourceVersion: "130"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system%3Acontroller%3Adeployment-controller
  uid: 69611d1d-4b26-11e9-8f3b-fa163eb7a9f3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:deployment-controller
subjects:
- kind: ServiceAccount
  name: deployment-controller
  namespace: kube-system
