apiVersion: v1
data:
  timeout-client: 60s
  timeout-client-fin: 60s
  timeout-server: 60s
  timeout-server-fin: 60s
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"name":"haproxy-configmap","namespace":"default"}}
  creationTimestamp: "2019-07-18T13:21:32Z"
  name: haproxy-configmap
  namespace: default
  resourceVersion: "16356392"
  selfLink: /api/v1/namespaces/default/configmaps/haproxy-configmap
  uid: f5c7fc35-a95e-11e9-858a-fa163eb7a9f3
