apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-03-26T23:26:52Z"
  generation: 4654
  labels:
    app: model
  name: model-deployment
  namespace: default
  resourceVersion: "15402737"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/model-deployment
  uid: a2d33b38-501e-11e9-8f3b-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: model
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - image: balazska/test-server:fixed-serving-v2
        imagePullPolicy: IfNotPresent
        name: test-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /media
          name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /media
          type: Directory
        name: log
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-03-26T23:26:52Z"
    lastUpdateTime: "2019-06-01T20:39:56Z"
    message: ReplicaSet "model-deployment-55485dbf7b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-15T15:16:25Z"
    lastUpdateTime: "2019-07-15T15:16:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4654
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
