apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"test"},"name":"test-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"test"}},"template":{"metadata":{"labels":{"app":"test"}},"spec":{"containers":[{"image":"balazska/test-server:fixed-serving","name":"test-server","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"300m"},"requests":{"cpu":"300m"}},"volumeMounts":[{"mountPath":"/media","name":"log"}]}],"volumes":[{"hostPath":{"path":"/media","type":"Directory"},"name":"log"}]}}}}
  creationTimestamp: "2019-07-18T14:40:56Z"
  generation: 26
  labels:
    app: test
  name: test-deployment
  namespace: default
  resourceVersion: "16842486"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/test-deployment
  uid: 0cfb95f2-a96a-11e9-858a-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: balazska/test-server:fixed-serving-v2
        imagePullPolicy: IfNotPresent
        name: test-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 300m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /media
          name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /media
          type: Directory
        name: log
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-18T14:40:56Z"
    lastUpdateTime: "2019-07-20T09:59:24Z"
    message: ReplicaSet "test-deployment-78dbc77b9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-26T13:06:01Z"
    lastUpdateTime: "2019-07-26T13:06:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
