apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-07-24T15:20:04Z"
  generation: 1
  name: fortio-deploy
  namespace: default
  resourceVersion: "16583644"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fortio-deploy
  uid: 830a56bd-ae26-11e9-858a-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fortio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc
      creationTimestamp: null
      labels:
        app: fortio
    spec:
      containers:
      - image: fortio/fortio:latest_release
        imagePullPolicy: Always
        name: fortio
        ports:
        - containerPort: 8080
          name: http-fortio
          protocol: TCP
        - containerPort: 8079
          name: grpc-ping
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: benchmark
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-24T15:20:07Z"
    lastUpdateTime: "2019-07-24T15:20:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-07-24T15:20:04Z"
    lastUpdateTime: "2019-07-24T15:20:07Z"
    message: ReplicaSet "fortio-deploy-568867d769" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
