apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nodejs-cpu"},"name":"nodejs-cpu-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nodejs-cpu"}},"template":{"metadata":{"labels":{"app":"nodejs-cpu"}},"spec":{"containers":[{"image":"balazska/nodejs_app:v1","name":"nodejs-app-cpu","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"100m"},"requests":{"cpu":"100m"}}}]}}}}
  creationTimestamp: "2019-07-27T12:16:08Z"
  generation: 129
  labels:
    app: nodejs-cpu
  name: nodejs-cpu-deployment
  namespace: default
  resourceVersion: "17017969"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nodejs-cpu-deployment
  uid: 5065e9a0-b068-11e9-858a-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-cpu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-cpu
    spec:
      containers:
      - image: balazska/nodejs_app:v1
        imagePullPolicy: IfNotPresent
        name: nodejs-app-cpu
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-27T12:16:08Z"
    lastUpdateTime: "2019-07-27T12:16:11Z"
    message: ReplicaSet "nodejs-cpu-deployment-867f545687" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-27T18:57:53Z"
    lastUpdateTime: "2019-07-27T18:57:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 129
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
