apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nodejs-ml"},"name":"nodejs-ml-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nodejs-ml"}},"template":{"metadata":{"labels":{"app":"nodejs-ml"}},"spec":{"containers":[{"image":"balazska/nodejs_app:v1","name":"nodejs-app-ml","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"100m"},"requests":{"cpu":"100m"}}}]}}}}
  creationTimestamp: "2019-07-27T12:17:55Z"
  generation: 32
  labels:
    app: nodejs-ml
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17023096"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodejs-ml-deployment
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-ml
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-ml
    spec:
      containers:
      - image: balazska/nodejs_app:v1
        imagePullPolicy: IfNotPresent
        name: nodejs-app-ml
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2019-07-27T12:17:55Z"
    lastUpdateTime: "2019-07-27T12:18:03Z"
    message: ReplicaSet "nodejs-ml-deployment-6d5565df57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-27T19:53:34Z"
    lastUpdateTime: "2019-07-27T19:53:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 32
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
