apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:03:42Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-l4rpd
  namespace: default
  resourceVersion: "17018375"
  uid: 40711bf8-b0a1-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:03:42Z"
message: Successfully assigned default/nodejs-ml-deployment-6d5565df57-l4rpd to worker-1
metadata:
  creationTimestamp: "2019-07-27T19:03:42Z"
  name: nodejs-ml-deployment-6d5565df57-l4rpd.15b558ed8e35d0ec
  namespace: default
  resourceVersion: "17018377"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-l4rpd.15b558ed8e35d0ec
  uid: 40729539-b0a1-11e9-858a-fa163eb7a9f3
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
