apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:52:28Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17022962"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:52:28Z"
message: 'Deleted pod: nodejs-ml-deployment-6d5565df57-l4rpd'
metadata:
  creationTimestamp: "2019-07-27T19:52:28Z"
  name: nodejs-ml-deployment-6d5565df57.15b55b96bce2c538
  namespace: default
  resourceVersion: "17022968"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b55b96bce2c538
  uid: 10464c20-b0a8-11e9-858a-fa163eb7a9f3
reason: SuccessfulDelete
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
