action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 5
deprecatedFirstTimestamp: "2019-07-27T12:44:58Z"
deprecatedLastTimestamp: "2019-07-27T19:12:45Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T18:39:31Z"
  name: nodejs-ml-deployment.15b5444296aea661
  namespace: default
  resourceVersion: "17019289"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment.15b5444296aea661
  uid: df347754-b09d-11e9-858a-fa163eb7a9f3
note: Scaled down replica set nodejs-ml-deployment-6d5565df57 to 2
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17015945"
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
