action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:12:45Z"
deprecatedLastTimestamp: "2019-07-27T19:12:45Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:12:45Z"
  name: nodejs-ml-deployment-6d5565df57.15b5596bf613d116
  namespace: default
  resourceVersion: "17019296"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b5596bf613d116
  uid: 840ca50d-b0a2-11e9-858a-fa163eb7a9f3
note: 'Deleted pod: nodejs-ml-deployment-6d5565df57-7d8zr'
reason: SuccessfulDelete
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17019286"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
