action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 11
deprecatedFirstTimestamp: "2019-07-27T12:19:56Z"
deprecatedLastTimestamp: "2019-07-27T19:53:31Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T18:28:57Z"
  name: nodejs-ml-deployment.15b542e4d3518da2
  namespace: default
  resourceVersion: "17023077"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment.15b542e4d3518da2
  uid: 65bc4798-b09c-11e9-858a-fa163eb7a9f3
note: Scaled up replica set nodejs-ml-deployment-6d5565df57 to 2
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17014887"
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
