apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:53:31Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-wtf5c
  namespace: default
  resourceVersion: "17023079"
  uid: 35e27064-b0a8-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:53:31Z"
message: Successfully assigned default/nodejs-ml-deployment-6d5565df57-wtf5c to worker-1
metadata:
  creationTimestamp: "2019-07-27T19:53:31Z"
  name: nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba56ef5070e
  namespace: default
  resourceVersion: "17023083"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba56ef5070e
  uid: 35e51cf4-b0a8-11e9-858a-fa163eb7a9f3
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
