apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:11:45Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-7d8zr
  namespace: default
  resourceVersion: "17019162"
  uid: 5f0b612e-b0a2-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:11:45Z"
message: Container image "balazska/nodejs_app:v1" already present on machine
metadata:
  creationTimestamp: "2019-07-27T19:11:45Z"
  name: nodejs-ml-deployment-6d5565df57-7d8zr.15b5595dcf88d151
  namespace: default
  resourceVersion: "17019175"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-7d8zr.15b5595dcf88d151
  uid: 5fd2d9b1-b0a2-11e9-858a-fa163eb7a9f3
reason: Pulled
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-2
type: Normal
