action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 695
deprecatedFirstTimestamp: "2019-07-26T10:07:37Z"
deprecatedLastTimestamp: "2019-07-27T19:53:46Z"
deprecatedSource:
  component: horizontal-pod-autoscaler
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:02:58Z"
  name: model-deployment.15b4ed17d8d27f7a
  namespace: default
  resourceVersion: "17023116"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/model-deployment.15b4ed17d8d27f7a
  uid: 25f0c23b-b0a1-11e9-858a-fa163eb7a9f3
note: 'unable to get metrics for resource cpu: no metrics returned from resource metrics
  API'
reason: FailedGetResourceMetric
regarding:
  apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  name: model-deployment
  namespace: default
  resourceVersion: "16997269"
  uid: a2ee29a0-501e-11e9-8f3b-fa163eb7a9f3
reportingInstance: ""
type: Warning
