action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:00:44Z"
deprecatedLastTimestamp: "2019-07-27T19:00:44Z"
deprecatedSource:
  component: kubelet
  host: worker-1
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:00:44Z"
  name: nodejs-ml-deployment-6d5565df57-ffq2g.15b558c3f182e5fc
  namespace: default
  resourceVersion: "17018072"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-ffq2g.15b558c3f182e5fc
  uid: d5eba4d1-b0a0-11e9-858a-fa163eb7a9f3
note: Started container
reason: Started
regarding:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-ffq2g
  namespace: default
  resourceVersion: "17018059"
  uid: d4a1a6a0-b0a0-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
