apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:11:43Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17019157"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:11:43Z"
message: 'Created pod: nodejs-ml-deployment-6d5565df57-62vmq'
metadata:
  creationTimestamp: "2019-07-27T19:11:43Z"
  name: nodejs-ml-deployment-6d5565df57.15b5595d8343efed
  namespace: default
  resourceVersion: "17019169"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b5595d8343efed
  uid: 5f129e80-b0a2-11e9-858a-fa163eb7a9f3
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
