apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:03:42Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17018371"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:03:42Z"
message: 'Created pod: nodejs-ml-deployment-6d5565df57-l4rpd'
metadata:
  creationTimestamp: "2019-07-27T19:03:42Z"
  name: nodejs-ml-deployment-6d5565df57.15b558ed8e21d5a0
  namespace: default
  resourceVersion: "17018378"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b558ed8e21d5a0
  uid: 4072d9a7-b0a1-11e9-858a-fa163eb7a9f3
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
