action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:12:46Z"
deprecatedLastTimestamp: "2019-07-27T19:12:46Z"
deprecatedSource:
  component: kubelet
  host: worker-2
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:12:46Z"
  name: nodejs-ml-deployment-6d5565df57-7d8zr.15b5596c05684ec7
  namespace: default
  resourceVersion: "17019301"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-7d8zr.15b5596c05684ec7
  uid: 8433d8d4-b0a2-11e9-858a-fa163eb7a9f3
note: Killing container with id docker://nodejs-app-ml:Need to kill Pod
reason: Killing
regarding:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-7d8zr
  namespace: default
  resourceVersion: "17019162"
  uid: 5f0b612e-b0a2-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
