apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:11:47Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-62vmq
  namespace: default
  resourceVersion: "17019165"
  uid: 5f0c89a7-b0a2-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:11:47Z"
message: Container image "balazska/nodejs_app:v1" already present on machine
metadata:
  creationTimestamp: "2019-07-27T19:11:47Z"
  name: nodejs-ml-deployment-6d5565df57-62vmq.15b5595e6b3bd15a
  namespace: default
  resourceVersion: "17019187"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-62vmq.15b5595e6b3bd15a
  uid: 6160c5d9-b0a2-11e9-858a-fa163eb7a9f3
reason: Pulled
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-3
type: Normal
