apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:52:28Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-l4rpd
  namespace: default
  resourceVersion: "17018376"
  uid: 40711bf8-b0a1-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:52:28Z"
message: Killing container with id docker://nodejs-app-ml:Need to kill Pod
metadata:
  creationTimestamp: "2019-07-27T19:52:28Z"
  name: nodejs-ml-deployment-6d5565df57-l4rpd.15b55b96d2d13484
  namespace: default
  resourceVersion: "17022972"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-l4rpd.15b55b96d2d13484
  uid: 107e1f77-b0a8-11e9-858a-fa163eb7a9f3
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-1
type: Normal
