action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:53:31Z"
deprecatedLastTimestamp: "2019-07-27T19:53:31Z"
deprecatedSource:
  component: default-scheduler
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:53:31Z"
  name: nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba56ef5070e
  namespace: default
  resourceVersion: "17023083"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba56ef5070e
  uid: 35e51cf4-b0a8-11e9-858a-fa163eb7a9f3
note: Successfully assigned default/nodejs-ml-deployment-6d5565df57-wtf5c to worker-1
reason: Scheduled
regarding:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-wtf5c
  namespace: default
  resourceVersion: "17023079"
  uid: 35e27064-b0a8-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
