action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T18:59:52Z"
deprecatedLastTimestamp: "2019-07-27T18:59:52Z"
deprecatedSource:
  component: kubelet
  host: worker-1
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T18:59:52Z"
  name: nodejs-cpu-deployment-867f545687-sx4z9.15b558b7d33e103b
  namespace: default
  resourceVersion: "17017970"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-cpu-deployment-867f545687-sx4z9.15b558b7d33e103b
  uid: b6e5f471-b0a0-11e9-858a-fa163eb7a9f3
note: Killing container with id docker://nodejs-app-cpu:Need to kill Pod
reason: Killing
regarding:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-cpu}
  kind: Pod
  name: nodejs-cpu-deployment-867f545687-sx4z9
  namespace: default
  resourceVersion: "17017748"
  uid: 6f1f7456-b0a0-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
