apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:12:45Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17019286"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:12:45Z"
message: 'Deleted pod: nodejs-ml-deployment-6d5565df57-7d8zr'
metadata:
  creationTimestamp: "2019-07-27T19:12:45Z"
  name: nodejs-ml-deployment-6d5565df57.15b5596bf613d116
  namespace: default
  resourceVersion: "17019296"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b5596bf613d116
  uid: 840ca50d-b0a2-11e9-858a-fa163eb7a9f3
reason: SuccessfulDelete
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
