apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:11:43Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-62vmq
  namespace: default
  resourceVersion: "17019163"
  uid: 5f0c89a7-b0a2-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:11:43Z"
message: Successfully assigned default/nodejs-ml-deployment-6d5565df57-62vmq to worker-3
metadata:
  creationTimestamp: "2019-07-27T19:11:43Z"
  name: nodejs-ml-deployment-6d5565df57-62vmq.15b5595d848bc7cd
  namespace: default
  resourceVersion: "17019171"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-62vmq.15b5595d848bc7cd
  uid: 5f157fd2-b0a2-11e9-858a-fa163eb7a9f3
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
