apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T18:59:42Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-78s4m
  namespace: default
  resourceVersion: "17014898"
  uid: 65bd39bd-b09c-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T18:59:42Z"
message: Killing container with id docker://nodejs-app-ml:Need to kill Pod
metadata:
  creationTimestamp: "2019-07-27T18:59:42Z"
  name: nodejs-ml-deployment-6d5565df57-78s4m.15b558b58b9ba374
  namespace: default
  resourceVersion: "17017943"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-78s4m.15b558b58b9ba374
  uid: b10fce43-b0a0-11e9-858a-fa163eb7a9f3
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-1
type: Normal
