apiVersion: v1
count: 5
eventTime: null
firstTimestamp: "2019-07-27T12:44:58Z"
involvedObject:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-ml-deployment
  namespace: default
  resourceVersion: "17015945"
  uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:12:45Z"
message: Scaled down replica set nodejs-ml-deployment-6d5565df57 to 2
metadata:
  creationTimestamp: "2019-07-27T18:39:31Z"
  name: nodejs-ml-deployment.15b5444296aea661
  namespace: default
  resourceVersion: "17019289"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment.15b5444296aea661
  uid: df347754-b09d-11e9-858a-fa163eb7a9f3
reason: ScalingReplicaSet
reportingComponent: ""
reportingInstance: ""
source:
  component: deployment-controller
type: Normal
