action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 64
deprecatedFirstTimestamp: "2019-07-27T12:18:08Z"
deprecatedLastTimestamp: "2019-07-27T18:57:51Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T12:18:08Z"
  name: nodejs-cpu-deployment.15b542cbc0ec2878
  namespace: default
  resourceVersion: "17017746"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-cpu-deployment.15b542cbc0ec2878
  uid: 97fe9db9-b068-11e9-858a-fa163eb7a9f3
note: Scaled up replica set nodejs-cpu-deployment-867f545687 to 2
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-cpu-deployment
  namespace: default
  resourceVersion: "16978253"
  uid: 5065e9a0-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
