apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:12:46Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-7d8zr
  namespace: default
  resourceVersion: "17019162"
  uid: 5f0b612e-b0a2-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:12:46Z"
message: Killing container with id docker://nodejs-app-ml:Need to kill Pod
metadata:
  creationTimestamp: "2019-07-27T19:12:46Z"
  name: nodejs-ml-deployment-6d5565df57-7d8zr.15b5596c05684ec7
  namespace: default
  resourceVersion: "17019301"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-7d8zr.15b5596c05684ec7
  uid: 8433d8d4-b0a2-11e9-858a-fa163eb7a9f3
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-2
type: Normal
