apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:11:43Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-7d8zr
  namespace: default
  resourceVersion: "17019161"
  uid: 5f0b612e-b0a2-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:11:43Z"
message: Successfully assigned default/nodejs-ml-deployment-6d5565df57-7d8zr to worker-2
metadata:
  creationTimestamp: "2019-07-27T19:11:43Z"
  name: nodejs-ml-deployment-6d5565df57-7d8zr.15b5595d829b4bf9
  namespace: default
  resourceVersion: "17019167"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-7d8zr.15b5595d829b4bf9
  uid: 5f0d48a6-b0a2-11e9-858a-fa163eb7a9f3
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
