apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T18:57:51Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-cpu-deployment-867f545687
  namespace: default
  resourceVersion: "17017743"
  uid: 50679cb2-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T18:57:51Z"
message: 'Created pod: nodejs-cpu-deployment-867f545687-sx4z9'
metadata:
  creationTimestamp: "2019-07-27T18:57:51Z"
  name: nodejs-cpu-deployment-867f545687.15b5589bca79bfbe
  namespace: default
  resourceVersion: "17017749"
  selfLink: /api/v1/namespaces/default/events/nodejs-cpu-deployment-867f545687.15b5589bca79bfbe
  uid: 6f215b73-b0a0-11e9-858a-fa163eb7a9f3
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
