apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:02:43Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-ffq2g
  namespace: default
  resourceVersion: "17018059"
  uid: d4a1a6a0-b0a0-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:02:43Z"
message: Killing container with id docker://nodejs-app-ml:Need to kill Pod
metadata:
  creationTimestamp: "2019-07-27T19:02:43Z"
  name: nodejs-ml-deployment-6d5565df57-ffq2g.15b558dfba57be1a
  namespace: default
  resourceVersion: "17018268"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-ffq2g.15b558dfba57be1a
  uid: 1d0c837f-b0a1-11e9-858a-fa163eb7a9f3
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-1
type: Normal
