apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:00:42Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17018053"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:00:42Z"
message: 'Created pod: nodejs-ml-deployment-6d5565df57-ffq2g'
metadata:
  creationTimestamp: "2019-07-27T19:00:42Z"
  name: nodejs-ml-deployment-6d5565df57.15b558c370fff5dd
  namespace: default
  resourceVersion: "17018060"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b558c370fff5dd
  uid: d4a2ab92-b0a0-11e9-858a-fa163eb7a9f3
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
