action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:11:43Z"
deprecatedLastTimestamp: "2019-07-27T19:11:43Z"
deprecatedSource:
  component: default-scheduler
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:11:43Z"
  name: nodejs-ml-deployment-6d5565df57-62vmq.15b5595d848bc7cd
  namespace: default
  resourceVersion: "17019171"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-62vmq.15b5595d848bc7cd
  uid: 5f157fd2-b0a2-11e9-858a-fa163eb7a9f3
note: Successfully assigned default/nodejs-ml-deployment-6d5565df57-62vmq to worker-3
reason: Scheduled
regarding:
  apiVersion: v1
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-62vmq
  namespace: default
  resourceVersion: "17019163"
  uid: 5f0c89a7-b0a2-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
