action: ""
apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2019-07-27T19:03:42Z"
deprecatedLastTimestamp: "2019-07-27T19:03:42Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2019-07-27T19:03:42Z"
  name: nodejs-ml-deployment-6d5565df57.15b558ed8e21d5a0
  namespace: default
  resourceVersion: "17018378"
  selfLink: /apis/events.k8s.io/v1beta1/namespaces/default/events/nodejs-ml-deployment-6d5565df57.15b558ed8e21d5a0
  uid: 4072d9a7-b0a1-11e9-858a-fa163eb7a9f3
note: 'Created pod: nodejs-ml-deployment-6d5565df57-l4rpd'
reason: SuccessfulCreate
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  resourceVersion: "17018371"
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
reportingInstance: ""
type: Normal
