apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T19:53:33Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{nodejs-app-ml}
  kind: Pod
  name: nodejs-ml-deployment-6d5565df57-wtf5c
  namespace: default
  resourceVersion: "17023082"
  uid: 35e27064-b0a8-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T19:53:33Z"
message: Started container
metadata:
  creationTimestamp: "2019-07-27T19:53:33Z"
  name: nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba5dd2d66d5
  namespace: default
  resourceVersion: "17023092"
  selfLink: /api/v1/namespaces/default/events/nodejs-ml-deployment-6d5565df57-wtf5c.15b55ba5dd2d66d5
  uid: 36ff2862-b0a8-11e9-858a-fa163eb7a9f3
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: worker-1
type: Normal
