apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2019-07-27T18:57:51Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: nodejs-cpu-deployment-867f545687-sx4z9
  namespace: default
  resourceVersion: "17017747"
  uid: 6f1f7456-b0a0-11e9-858a-fa163eb7a9f3
kind: Event
lastTimestamp: "2019-07-27T18:57:51Z"
message: Successfully assigned default/nodejs-cpu-deployment-867f545687-sx4z9 to worker-1
metadata:
  creationTimestamp: "2019-07-27T18:57:51Z"
  name: nodejs-cpu-deployment-867f545687-sx4z9.15b5589bcb7cff7e
  namespace: default
  resourceVersion: "17017751"
  selfLink: /api/v1/namespaces/default/events/nodejs-cpu-deployment-867f545687-sx4z9.15b5589bcb7cff7e
  uid: 6f23eb68-b0a0-11e9-858a-fa163eb7a9f3
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
