apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"test-ingress","namespace":"default"},"spec":{"rules":[{"host":"testserver","http":{"paths":[{"backend":{"serviceName":"test-service","servicePort":8080},"path":"/"}]}}]}}
  creationTimestamp: "2019-07-18T14:40:56Z"
  generation: 1
  name: test-ingress
  namespace: default
  resourceVersion: "15795272"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/test-ingress
  uid: 0d0562cd-a96a-11e9-858a-fa163eb7a9f3
spec:
  rules:
  - host: testserver
    http:
      paths:
      - backend:
          serviceName: test-service
          servicePort: 8080
        path: /
status:
  loadBalancer: {}
