apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-07-27T19:53:31Z"
  generateName: nodejs-ml-deployment-6d5565df57-
  labels:
    app: nodejs-ml
    pod-template-hash: 6d5565df57
  name: nodejs-ml-deployment-6d5565df57-wtf5c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nodejs-ml-deployment-6d5565df57
    uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
  resourceVersion: "17023094"
  selfLink: /api/v1/namespaces/default/pods/nodejs-ml-deployment-6d5565df57-wtf5c
  uid: 35e27064-b0a8-11e9-858a-fa163eb7a9f3
spec:
  containers:
  - image: balazska/nodejs_app:v1
    imagePullPolicy: IfNotPresent
    name: nodejs-app-ml
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kh6h8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-kh6h8
    secret:
      defaultMode: 420
      secretName: default-token-kh6h8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T19:53:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T19:53:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T19:53:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T19:53:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a969027e0893abfdac4587661166391671fa08b265ebf761e120b28ff73657e4
    image: balazska/nodejs_app:v1
    imageID: docker-pullable://balazska/nodejs_app@sha256:e4cb31444ababd3dfb7150f4847531a25fafe80d8642d09b56590dfb2007fd6f
    lastState: {}
    name: nodejs-app-ml
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-27T19:53:33Z"
  hostIP: 172.16.0.13
  phase: Running
  podIP: 10.44.0.2
  qosClass: Burstable
  startTime: "2019-07-27T19:53:31Z"
