apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-07-27T12:16:08Z"
  generateName: nodejs-cpu-deployment-867f545687-
  labels:
    app: nodejs-cpu
    pod-template-hash: 867f545687
  name: nodejs-cpu-deployment-867f545687-mbxnt
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nodejs-cpu-deployment-867f545687
    uid: 50679cb2-b068-11e9-858a-fa163eb7a9f3
  resourceVersion: "16978047"
  selfLink: /api/v1/namespaces/default/pods/nodejs-cpu-deployment-867f545687-mbxnt
  uid: 506ac983-b068-11e9-858a-fa163eb7a9f3
spec:
  containers:
  - image: balazska/nodejs_app:v1
    imagePullPolicy: IfNotPresent
    name: nodejs-app-cpu
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kh6h8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-3
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-kh6h8
    secret:
      defaultMode: 420
      secretName: default-token-kh6h8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T12:16:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T12:16:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T12:16:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-27T12:16:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://df0a2f9dad1e7855b122ebd4558c0c1a431cba6aa5506795fd20c52125ba158b
    image: balazska/nodejs_app:v1
    imageID: docker-pullable://balazska/nodejs_app@sha256:e4cb31444ababd3dfb7150f4847531a25fafe80d8642d09b56590dfb2007fd6f
    lastState: {}
    name: nodejs-app-cpu
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-27T12:16:10Z"
  hostIP: 172.16.0.7
  phase: Running
  podIP: 10.42.0.8
  qosClass: Burstable
  startTime: "2019-07-27T12:16:08Z"
