apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-06-01T20:39:50Z"
  generateName: model-deployment-55485dbf7b-
  labels:
    app: model
    pod-template-hash: 55485dbf7b
  name: model-deployment-55485dbf7b-hvh4f
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: model-deployment-55485dbf7b
    uid: 67468f30-84ad-11e9-8f3b-fa163eb7a9f3
  resourceVersion: "9476938"
  selfLink: /api/v1/namespaces/default/pods/model-deployment-55485dbf7b-hvh4f
  uid: 67497365-84ad-11e9-8f3b-fa163eb7a9f3
spec:
  containers:
  - image: balazska/test-server:fixed-serving-v2
    imagePullPolicy: IfNotPresent
    name: test-server
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /media
      name: log
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kh6h8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /media
      type: Directory
    name: log
  - name: default-token-kh6h8
    secret:
      defaultMode: 420
      secretName: default-token-kh6h8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-06-01T20:39:50Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-06-01T20:39:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-06-01T20:39:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-06-01T20:39:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://25a8a86f24b9e2df23904a2795e05c0735fa9299e655abb5d02b571ce2d845aa
    image: balazska/test-server:fixed-serving-v2
    imageID: docker-pullable://balazska/test-server@sha256:14ae8d1ed79e5a55cd72d5fb3fb062cbee701a4744f4b88e04852bffca2cc503
    lastState: {}
    name: test-server
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-06-01T20:39:55Z"
  hostIP: 172.16.0.19
  phase: Running
  podIP: 10.36.0.1
  qosClass: Burstable
  startTime: "2019-06-01T20:39:50Z"
