apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-07-18T14:40:56Z"
  generation: 2
  labels:
    app: test
    pod-template-hash: 85569dbf86
  name: test-deployment-85569dbf86
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: test-deployment
    uid: 0cfb95f2-a96a-11e9-858a-fa163eb7a9f3
  resourceVersion: "16031455"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/test-deployment-85569dbf86
  uid: 0cfd6de6-a96a-11e9-858a-fa163eb7a9f3
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test
      pod-template-hash: 85569dbf86
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
        pod-template-hash: 85569dbf86
    spec:
      containers:
      - image: balazska/test-server:fixed-serving
        imagePullPolicy: IfNotPresent
        name: test-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 300m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /media
          name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /media
          type: Directory
        name: log
status:
  observedGeneration: 2
  replicas: 0
