apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2019-06-01T13:06:07Z"
  generation: 2
  labels:
    app: model
    pod-template-hash: 67867fbb8c
  name: model-deployment-67867fbb8c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: model-deployment
    uid: a2d33b38-501e-11e9-8f3b-fa163eb7a9f3
  resourceVersion: "9476948"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/model-deployment-67867fbb8c
  uid: 051da0f8-846e-11e9-8f3b-fa163eb7a9f3
spec:
  replicas: 0
  selector:
    matchLabels:
      app: model
      pod-template-hash: 67867fbb8c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
        pod-template-hash: 67867fbb8c
    spec:
      containers:
      - image: balazska/test-server:fixed-serving
        imagePullPolicy: IfNotPresent
        name: test-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /media
          name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /media
          type: Directory
        name: log
status:
  observedGeneration: 2
  replicas: 0
