apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-07-27T12:17:55Z"
  generation: 32
  labels:
    app: nodejs-ml
    pod-template-hash: 6d5565df57
  name: nodejs-ml-deployment-6d5565df57
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nodejs-ml-deployment
    uid: 90832e74-b068-11e9-858a-fa163eb7a9f3
  resourceVersion: "17023095"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/nodejs-ml-deployment-6d5565df57
  uid: 908511a8-b068-11e9-858a-fa163eb7a9f3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-ml
      pod-template-hash: 6d5565df57
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-ml
        pod-template-hash: 6d5565df57
    spec:
      containers:
      - image: balazska/nodejs_app:v1
        imagePullPolicy: IfNotPresent
        name: nodejs-app-ml
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 32
  readyReplicas: 2
  replicas: 2
